name: Release new major version
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    container:
      image: bartkl/nbnl-env
      ports:
        - 8080
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Tag version
        run: |
          git config --global --add safe.directory /__w/edsn-linkml-poc/edsn-linkml-poc
          git fetch && git fetch --tags

          LATEST_MAJOR=$(echo ${{ github.ref_name }} | cut -c 2- | cut -d . -f 1)
          NEW_MAJOR=$(echo $LATEST_MAJOR + 1 | bc)
          NEW_VERSION=$(echo v$NEW_MAJOR.0.0)

          git config user.name "CICD"
          git config user.email "cicd@edsn.nl"

          git checkout -b v$NEW_MAJOR
          git tag $NEW_VERSION
          git push -u origin v$NEW_MAJOR && git push --tags
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: Generate documentation and schemas
        run: |
          VERSION=${{ env.NEW_VERSION }} just build
      - name: Commit artifacts to `docs` branch
        run: |
          git fetch
          git checkout docs

          if [ -d "${{ env.NEW_VERSION }}" ]; then
              exit 1  # Versions are set in stone.
          fi

          sed -i '/^version: .*$/d' artifacts/documentation/antora.yml
          sed -i "/^name: .*$/a version: ${{ env.NEW_VERSION }}" artifacts/documentation/antora.yml

          mv artifacts/documentation "${{ env.NEW_VERSION }}"

          git config user.name "CICD"
          git config user.email "cicd@netbeheernederland.nl"

          git add "${{ env.NEW_VERSION }}"
          git commit -m "Added docs and schemas for ${{ env.NEW_VERSION }}"
          git push
      - name: Prepare release
        run: echo "" > release_notes.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release_notes.txt
          tag_name: ${{ env.NEW_VERSION }}
          files: |
            ${{ env.NEW_VERSION }}/modules/schema/attachments/information_models/*.schema.linkml.yml
            ${{ env.NEW_VERSION }}/modules/schema/attachments/schemas/*/*
